function plot_vsESM(dsValue_map, obsValue_test_map, ESM_map, ...
    flag_land, lat, lon, bias_limit, bias_step, ...
    palette_bias, path_shp_file, res_fig, ...
    ds_label, esm_label, unit_var, text_title,...
    lim_lat, lim_lon, n_color_bias, path_fig, suffix)

% Reshape maps to space x time if needed
if ndims(dsValue_map) == 3
    dsValue_map = reshape(dsValue_map, [], size(dsValue_map, 3));
    obsValue_test_map = reshape(obsValue_test_map, [], size(obsValue_test_map, 3));
    ESM_map = reshape(ESM_map, [], size(ESM_map, 3));
end
tgt_size = [length(lon) length(lat)];

% --- Plot PCR bias ---
plot_single(mean(dsValue_map - obsValue_test_map, 2, 'omitnan'), ...
    tgt_size, flag_land, lat, lon, bias_limit, bias_step, ...
    palette_bias(n_color_bias), path_shp_file, res_fig, ...
    text_title, ds_label, unit_var, lim_lat, lim_lon, path_fig, suffix);

% --- Plot ESM bias ---
plot_single(mean(ESM_map - obsValue_test_map, 2, 'omitnan'), ...
    tgt_size, flag_land, lat, lon, bias_limit, bias_step, ...
    palette_bias(n_color_bias), path_shp_file, res_fig, ...
    text_title, esm_label, unit_var, lim_lat, lim_lon, path_fig, suffix);

end